### ISSUE TITLE
add new feature

### ISSUE THREAD

**Issue by jiggusuperking** [scp222thj/MalumMenu#100]
can you add these features to mod:
1.other player role changing 
2.ban player or kick player form the lobby on find game
3.add shapeshifter on roles {not on settings} {on change role button}
4.other player vision to 0 

pls make these features

**Comment by LilianPontes35** [comment]
**first resort :

This can only be done by the host; if you perform this function, you will be banned from the room.

But the creator can put this in the menu

---------------------------------------------------------------
Creator, I have the code to add this to the menu 
--------------------------------------------------------------

second feature :
Impossible to do this because the among us server has been updated to stop people using Kick Exploit.

third feature :
The Shapeshifter function can only be used if it has already been assigned at the start of the game
This is done to prevent the anticheat from kicking your player


last resort:

You can only do this if you are the host; if you do, everyone will have a 0 ate view of you.
We need to study this to leave only one player with 0 vision**

**Comment by astra1dev** [comment]
bro if you have code open a pr 😂
