### ISSUE TITLE
XGM Support?

### ISSUE THREAD

**Issue by oIKR2** [scp222thj/MalumMenu#12]
I am unsure about pretty much everything. I followed all steps on instructions, and I did put the files, but nothing really happens. I checked my inventory and I have the same cosmetics as before. I believe its because I just the Micosoft Store/Xbox Gamepass version. Is there even support for it?

**Comment by scp222thj** [comment]
After a bit of research, from what I understand installing mods on Microsoft Store games is indeed very hard because Windows basically locks the Microsoft Store apps folder with special permissions. 

I found a few forum posts from people with a similar issue, maybe these might help:

[Forum post 1](https://answers.microsoft.com/en-us/windows/forum/all/among-us-mod-install/7d765544-d394-47a8-b450-8ee7e8cb0970)
[Forum post 2](https://answers.microsoft.com/en-us/windows/forum/all/among-us-microsoft-store-mods/ad341824-0673-4882-893f-7c66cbcc7c53)

**Comment by oIKR2** [comment]
I believe among us is stored on C:\XboxGames\Among Us\Content. I also managed to get the perms for among us. Here are the files. https://www.mediafire.com/file/hezy6x4iuym0jmg/amogus.zip/file you could scan them with virus total if you want. I also have a cheat table for among us XGM https://www.mediafire.com/file/fspw5srqbpg2ize/AmogusHacks.ct/file

**Comment by scp222thj** [comment]
If you have already obtained the perms to edit that Among Us folder you sent me, then you should just be able to extract the contents of the [MalumMenu ZIP file](https://github.com/scp222thj/MalumMenu/releases/download/v1.1.2/MalumMenu-1.1.2.zip) into it. (If the file extraction works correctly, you should be able to see a "BepInEx" folder next to "Among Us_Data")
