### ISSUE TITLE
Cracked version support

### ISSUE THREAD

**Issue by Shadow-Knight89** [scp222thj/MalumMenu#132]
hello ,I'm very interested in your cheat, i read the features and they are just so good. but i have a problem using it. in the country i live, (Iran) the economy is so bad that if i want to buy the game legally i need to give my whole income of 2 months working 8 hours a day and 5 days in a week, so i just couldn't do that so i installed the cracked version, but this cheat does NOT work on the cracked version of game. i would like to know if someone could help me. i really need your helps. thanks for reading.

**Comment by astra1dev** [comment]
#ReadTheReadme
cracked version isnt supported

**Comment by Shadow-Knight89** [comment]
do you think i don't know?! i know it but if you read full of my issue, you would know what i'm saying!

**Comment by astra1dev** [comment]
I read your issue. Unfortunately I have to tell you there is NOTHING to help, MalumMenu does NOT WORK for cracked version and there is nothing to do about it!!

I would also like to remind you piracy is illegal. 
Have a nice day.

**Comment by LilianPontes35** [comment]
O menu malum funciona em uma versão crackeada. porque entre nós o crack é como uma versão portátil de uma das versões do entre nós.

**Comment by astra1dev** [comment]
I am a contributor to this project. When i say MM does not work on cracked, it does not work. Fact. 


Also instead of saying
> i would like to know if someone could help me. i really need your helps.

and

> i have a problem using it.

you could just say what issue exactly youre having. That would speed up the process of helping a lot. For more information check this site: https://dontasktoask.com Please follow it when you are asking questions or having issues in the future. Thanks.
