### ISSUE TITLE
Pls dont release the kick player feature

### ISSUE THREAD

**Issue by NikoCat233** [scp222thj/MalumMenu#47]
Its too OP and will 100% make innersloth very angry

**Comment by NikoCat233** [comment]
I coded this feature for fun and learning in my fork, but the developer force mergerd it.
I personally wont use this to do bad thing, but I doubt if this is open to public , it will cause serious issues.
As this feature provides ways for some people with bad intentions to crash any room with out being acknowledged.

**Comment by Gurge44** [comment]
Yes please don't release a feature like this.... If hosting a modded room with Innersloth's protocol isn't already hard enough, this would totally make everyone mad and I can't see any good outcome if it gets released.... Please don't.

**Comment by scp222thj** [comment]
@NikoCat233 Although I was inspired by your implementation (I gave you credit for this ofc), the way I coded it into the menu is completely different and unrelated, so I promise that I didn't "forge-merge" or steal anything from your fork. Having said that, I'm sorry if it made you uncomfortable, I had no idea you preferred to keep the exploit private.

I'm sorry that some of you are worried about the release of this cheat, but I don't think there is any point in removing it from the menu now. Since I've already commited the code, it is now public and even if I were to remove it, it would still be accessible by anyone in this repo's commits. 

I also personally don't believe gatekeeping exploits is any good. It is not the community's responsibility to keep Among Us safe by hiding its vulnerabilities, I think Innersloth should be the ones working to secure their game if they don't want people messing with it.

And also, if I won't release this cheat, I am sure that some other cheat developer out there would find it and release it anyway pretty soon, since it's quite an obvious vulnerability in the way the game handles RPC calls from clients. In fact, using the simple concept from this exploit, I have already been able to discover a series of other exploits (like sending chat messages as other people).

**Comment by NikoCat233** [comment]
Welp, I personally will report this exploit to InnerSloth, though they will probably delay a whole month to fix it.
I posted here simply bcz this exploit is too destructive while my initail idea is for fun and learning, I dont want mads to spread around.
