### ISSUE TITLE
how find AmongUs.GameLibs.Steam

### ISSUE THREAD

**Issue by pjy612** [scp222thj/MalumMenu#9]
how find or dump AmongUs.GameLibs.Steam ?

**Comment by scp222thj** [comment]
Why? What's the problem?

**Comment by pjy612** [comment]
no problem, just thought I'd ask.
I'd like to expand on the source to add some functionality and see what happens, but from the project AmongUs.GameLibs.Steam doesn't seem to be on nuget, so I'd like to ask how to extract it.
I've never looked into il2cpp before...only learned mono.

**Comment by scp222thj** [comment]
You can find deobfuscated assemblies for the latest Among Us version in [this](https://reactor.gg/discord) modding Discord server (in the #resources channel). Just download the latest DLL and use a C# decompiler like dnSpy to read its code. To learn more on Among Us modding you can find useful guides [here](https://docs.reactor.gg) (however I don't recommend using the Reactor modding api when making Among Us mods because it doesn't work on public unmodded lobbies)

**Comment by pjy612** [comment]
I found that the nuget package is on `nuget.bepinex.dev`, adding a new source for the package should be fine

**Comment by pjy612** [comment]
By the way, it is recommended that the shortcut for triggering the window be set to be configurable using Config.

**Comment by scp222thj** [comment]
> I found that the nuget package is on `nuget.bepinex.dev`, adding a new source for the package should be fine

Isn't this package already present in nuget.config and MalumMenu.csproj?

> By the way, it is recommended that the shortcut for triggering the window be set to be configurable using Config.Bind

That's an interesting idea that I might implement in the future, since as you can see from some of the other open issues the DELETE key doesn't seem to be working for some people

**Comment by pjy612** [comment]
> 这个包是否已存在于[nuget.config](https://github.com/scp222thj/MalumMenu/blob/main/nuget.config)和[MalumMenu.csproj](https://github.com/scp222thj/MalumMenu/blob/main/src/MalumMenu.csproj)中？
> 
I apologize for my oversight.
